# Generated by Django 4.1.5 on 2023-01-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitebackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
