# Generated by Django 4.1.5 on 2023-01-08 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitebackend', '0002_shoppingcartproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartproduct',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcartproduct',
            unique_together={('product', 'shopping_cart')},
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitebackend.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitebackend.product')),
            ],
        ),
    ]
